# 07/01

## Importing

In [1]:
import math
math.sqrt(25)

5.0

In [2]:
import math as m
m.sqrt(25)

5.0

In [3]:
from math import sqrt
sqrt(25)

5.0

In [6]:
from numpy.random import randint
randint(1, 101, 10)

array([38, 72,  1, 60, 36, 48, 40, 14, 46, 93])

In [5]:
np.random.randint(1, 101, 10)

NameError: name 'np' is not defined

In [6]:
from numpy.random import randn
randn(10)

array([ 0.29012462,  0.13517461,  1.27674849,  0.7911159 , -0.89870851,
        0.24360839, -0.4945206 , -0.81196533, -0.68038628,  1.47166107])

In [7]:
randn(3,3)

array([[ 1.2458823 ,  1.13259332, -1.16798428],
       [ 1.4992351 ,  0.90824443,  0.78376763],
       [ 0.71372407,  1.3037277 , -0.08500715]])

In [8]:
import sys
b = 10
sys.getsizeof(10)

28

In [9]:
c = ''
sys.getsizeof(c)

49

In [10]:
l = []
sys.getsizeof(l)

64

In [11]:
l = [0]
sys.getsizeof(l)

72

## Numpy Arrays

### Advantages
1. Can create multi-dimesional arrays
2. Faster mathematical operations

In [44]:
import numpy as np

In [45]:
# Creating arrays using ranges

a = np.arange(10)
print(type(a))
a

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
print(np.arange(2, 16))
print(np.arange(2, 16, 2))

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14]


In [47]:
a[4]

4

In [48]:
a[-1]

9

In [49]:
a[2:6]

array([2, 3, 4, 5])

In [50]:
a[-4:-8:-1]

array([6, 5, 4, 3])

### Reshaping

In [51]:
a = np.arange(1, 10)
print(a)
b = a.reshape(3, 3)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.arange(10).reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [54]:
a5 = np.arange(5, 51, 5).reshape(5, 2)
a5

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])

In [55]:
a5[2][0]

25

In [56]:
len(a5)

5

In [57]:
a5.shape

(5, 2)

In [58]:
a5.size

10

### Array Operations

In [59]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])

* Does element wise addition instead of concatenation (like in Lists)

In [60]:
arr1 + arr2

array([5, 5, 5, 5])

In [61]:
arr1 - arr2

array([-3, -1,  1,  3])

In [62]:
arr1 * arr2

array([4, 6, 6, 4])

In [63]:
arr1 / arr2

array([0.25      , 0.66666667, 1.5       , 4.        ])

In [66]:
arr1 // arr2

array([0, 0, 1, 4], dtype=int32)

In [69]:
arr1 % arr2

array([1, 2, 1, 0], dtype=int32)

In [70]:
arr1 ** arr2

array([1, 8, 9, 4], dtype=int32)

In [71]:
arr3 = np.array([[1,2,3,4], [5,6,7,8]])
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
import numpy as np

In [18]:
# Dot product
arr1 = np.random.randint(0,11,9).reshape(3,3)
arr1

array([[10, 10,  0],
       [ 8,  9,  7],
       [ 1,  3,  0]])

In [19]:
arr1.T

array([[10,  8,  1],
       [10,  9,  3],
       [ 0,  7,  0]])

In [24]:
arr1@arr1.T  #like mulitiplication array

array([[200, 170,  40],
       [170, 194,  35],
       [ 40,  35,  10]])

In [25]:
arr1.dot(arr1.T)

array([[200, 170,  40],
       [170, 194,  35],
       [ 40,  35,  10]])

### Slicing

In [77]:
a = np.arange(1,31).reshape(5,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [78]:
a[0]

array([1, 2, 3, 4, 5, 6])

In [79]:
a[0,0]

1

In [80]:
a[1:3]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [81]:
a[:3]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [82]:
a[:,0]

array([ 1,  7, 13, 19, 25])

In [83]:
a[:,2:4]

array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22],
       [27, 28]])

In [84]:
a[:,:3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [85]:
a[:, [0,3]]

array([[ 1,  4],
       [ 7, 10],
       [13, 16],
       [19, 22],
       [25, 28]])

In [86]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [87]:
a[1:3, 1:4]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [88]:
a[3:,4:]

array([[23, 24],
       [29, 30]])

In [89]:
a[-1,-1]

30

In [90]:
a[-2, -4]

21

In [95]:
a[0, 1::2]

array([2, 4, 6])

In [96]:
a[1::2,1::2]

array([[ 8, 10, 12],
       [20, 22, 24]])

In [97]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
a[0:8:3]

array([1, 4, 7])

In [99]:
a[-2:-7:-2]

array([9, 7, 5])

In [101]:
# Compare speed of operations in lists and numpy arrays

import sys
import time
import numpy as np

def list_add(l1, l2):
    i = 0
    for a in l2:
        l1[i] = l1[i] + 1
        i = i + 1
        
count = 100000

l1 = list(range(count))
l2 = list(range(count))

start = time.time()
list_add(l1, l2)
end = time.time()

elapsed = 1000*(end-start)
print("List addition time is", elapsed)

a1 = np.arange(count)
a2 = np.arange(count)

start = time.time()
a3 = a1 + a2
end = time.time()

elapsed = 1000*(end-start)
print("Array addition time is", elapsed)

List addition time is 17.953157424926758
Array addition time is 0.9968280792236328


### Zero, One, Identity matrices

In [102]:
# by default it gives floats; set dtype to int to get ints
a = np.zeros(6, dtype=int).reshape(2,3)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [103]:
b = np.ones(6, dtype=int).reshape(2,3)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [104]:
c = np.eye(4, dtype=int)
c

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Concatenation

In [105]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
# concatenate numpy arrays
np.concatenate([arr1,arr1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
# default is row wise
np.concatenate([arr1,arr1], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
# column wise concatenation
np.concatenate([arr1,arr1], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

### Stack

In [109]:
a = np.array([3,1,2])
b = np.array([5,6,7])
c0 = np.stack((a,b))
c0

array([[3, 1, 2],
       [5, 6, 7]])

In [110]:
c0.shape

(2, 3)

In [111]:
c1 = np.stack((a,b), axis=1)
c1

array([[3, 5],
       [1, 6],
       [2, 7]])

In [112]:
c1.shape

(3, 2)

### Column Stack

In [113]:
c = np.column_stack((a,b))
c

array([[3, 5],
       [1, 6],
       [2, 7]])

In [114]:
c.shape

(3, 2)

In [30]:
a = np.array([3,1,2,4,4])
b = np.array([5,6,7,5,6])

### Depth Stack

In [31]:
d = np.dstack((a,b))
d

array([[[3, 5],
        [1, 6],
        [2, 7],
        [4, 5],
        [4, 6]]])

In [116]:
d.shape

(1, 3, 2)

### Horizontal Stack

In [32]:
h = np.hstack((a,b))
h

array([3, 1, 2, 4, 4, 5, 6, 7, 5, 6])

In [35]:
h.shape

(10,)

### Vertical Stack

In [36]:
v = np.vstack((a,b))
v

array([[3, 1, 2, 4, 4],
       [5, 6, 7, 5, 6]])

In [37]:
v.shape

(2, 5)

### Block

In [39]:
np.block([a,b])

array([3, 1, 2, 4, 4, 5, 6, 7, 5, 6])

In [40]:
np.block([a,b,32])

array([ 3,  1,  2,  4,  4,  5,  6,  7,  5,  6, 32])

In [42]:
np.block([32,b,a])

array([32,  5,  6,  7,  5,  6,  3,  1,  2,  4,  4])

In [45]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
a.reshape(4,7)

ValueError: cannot reshape array of size 11 into shape (4,7)

In [43]:
np.block([a,0]).reshape(3,4)

ValueError: cannot reshape array of size 6 into shape (3,4)

### Split

In [57]:
a = np.arange(10)
np.split(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [129]:
np.split(a,3)

ValueError: array split does not result in an equal division

In [130]:
np.split(a,[2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [5]:
np.split(a,[3,7,8])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7]), array([8, 9])]

### Array Split

In [6]:
np.array_split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [58]:
np.array_split(a,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

### Statistical Operations

In [60]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a.sum()

45

In [62]:
a.mean()

5.0

In [63]:
a.mean(0) # x axis

array([4., 5., 6.])

In [64]:
a.mean(1) # y axis

array([2., 5., 8.])

In [65]:
a.std()

2.581988897471611

In [66]:
a.std(0)

array([2.44948974, 2.44948974, 2.44948974])

In [88]:
a.std(1)

array([0.81649658, 0.81649658, 0.81649658])

In [89]:
a.var()

6.666666666666667

In [90]:
a.var(0)

array([6., 6., 6.])

In [91]:
a.var(1)

array([0.66666667, 0.66666667, 0.66666667])

In [92]:
a = np.random.randint(1,101, 10)
a

array([83, 55, 12, 89, 76, 57, 29, 83, 54, 71])

In [93]:
a.max()

89

In [94]:
a.min()

12

In [14]:
arr1 = np.random.randint(1,101,10)
arr2 = np.random.randint(1,101,10)

In [15]:
arr1

array([43, 78, 95, 45,  5, 26, 45, 53,  7,  5])

In [16]:
arr2

array([ 71,  67,  28,  86,  49,  11,  78,  10, 100,  28])

In [17]:
np.maximum(arr1, arr2)

array([ 71,  78,  95,  86,  49,  26,  78,  53, 100,  28])

In [18]:
arr1.max()

95

# 07/02

### Horizontal Split

In [67]:
mat = np.arange(1,13).reshape(3,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
hs = np.hsplit(mat, np.array([3]))
hs

[array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]]), array([[ 4],
        [ 8],
        [12]])]

In [99]:
hs[0]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [100]:
hs[1]

array([[ 4],
       [ 8],
       [12]])

### Vertical Split

In [101]:
vs = np.vsplit(mat, np.array([2]))
vs

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [102]:
vs[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
vs[1]

array([[ 9, 10, 11, 12]])

### Iteration

In [104]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

for row in mat:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [105]:
for row in mat:
    for cell in row:
        print(cell)

1
2
3
4
5
6
7
8
9


### Conditional Statements (Boolean Arrays)

In [106]:
ca = np.arange(9).reshape(3,3)
print("The original array is \n",ca)

con = ca > 5

print("\nThe boolean array after the conditional statement is apllied \n")
print(con)

ca[con] # prints only numbers satisfying the condition

The original array is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

The boolean array after the conditional statement is apllied 

[[False False False]
 [False False False]
 [ True  True  True]]


array([6, 7, 8])

In [107]:
ca[ca>4] = 0
print(ca)

[[0 1 2]
 [3 4 0]
 [0 0 0]]


### Where

In [20]:
a = np.array([1,2,3,4])
b = np.array([100,200,300,400])
c = np.array([True,False,True,False])

In [24]:
# if condition is true it takes values of first array, else from second array
np.where(c,a,b)

array([  1, 200,   3, 400])

In [25]:
arr1 = np.random.randint(1,101,10)

In [26]:
arr1

array([45, 92, 73, 83, 35, 12, 91, 28, 86, 75])

In [28]:
# returns all indices where the condition is true
np.where(arr1>50)

(array([1, 2, 3, 6, 8, 9], dtype=int64),)